language: node_js
node_js:
  - "6"
dist: trusty
sudo: required 
before_install:
  - npm install -g node-gyp
env:
  - CXX=g++-5
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
compiler:
  - clang
  - gcc
script:
  - npm install
  - npm run test
after_success: npm run coverage
